version: "3.3"

services:
  databasecx:
    image: mariadb
    volumes:
      - ./database/sql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sample
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: samplepass
      MYSQL_ROOT_HOST: '%'
    ports:
     - "3306:3306"

  websitecx:
    depends_on:
      - databasecx
    image: php:7.2-apache
    volumes:
      - ./../:/var/www/html
    ports:
      - "80:80"
    links:
      - databasecx

volumes:
  db_data: {}